In [1]:
import torch

In [2]:
x = torch.tensor([1,2,3])

print(x)

tensor([1, 2, 3])


In [3]:
print(x.shape)

torch.Size([3])


In [4]:
print(x.dtype)

torch.int64


In [5]:
print(x.device)

cpu


In [7]:
x = torch.arange(12)

print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [8]:
y = x.reshape(3,4)

print(y)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [9]:
print(y.shape)

torch.Size([3, 4])


In [10]:
print(y[0])

tensor([0, 1, 2, 3])


In [11]:
print(y[:,1])

tensor([1, 5, 9])
