In [ ]:
import torch

a = torch.arange(6)
# aは、0-5までの数字が入ったtensor
print(a)
# a.shapeは、tensorの形(サイズ)を表す。1次元で要素が6個ある
print(a.shape)

tensor([0, 1, 2, 3, 4, 5])
torch.Size([6])


In [ ]:
# reshapeは、Tensorの形(数字の列や行)を変える
b = a.reshape(2,3)

print(b)
print(b.shape)

tensor([[0, 1, 2],
        [3, 4, 5]])
torch.Size([2, 3])


In [ ]:
import torch

x=torch.tensor([1,2,3])

print(x +1) # メモ: [1+1, 2+1, 3+1] -> 全部のに+1される
print(x * 2) # メモ: [1*2, 2*2, 3*2] -> 全部のが2倍される
print(x - 1) # メモ: [1-1, 2-1, 3-1] -> 全部から-1される
print(x / 2) # メモ: [1/2, 2/2, 3/2] -> 割り算すると自動で小数(float)になる！

tensor([2, 3, 4])
tensor([2, 4, 6])
tensor([0, 1, 2])
tensor([0.5000, 1.0000, 1.5000])


In [ ]:
y = torch.tensor([10,20,30])

print(x + y) # メモ: 同じ位置同士を足す [1+10, 2+20, 3+30] -> [11, 22, 33]
print(x * y)  # メモ: 同じ位置同士を掛ける [1*10, 2*20, 3*30] -> [10, 40, 90]

tensor([11, 22, 33])
tensor([10, 40, 90])
