In [ ]:
import torch

a = torch.arange(6)
# aは、0-5までの数字が入ったtensor
print(a)
# a.shapeは、tensorの形(サイズ)を表す。1次元で要素が6個ある
print(a.shape)

tensor([0, 1, 2, 3, 4, 5])
torch.Size([6])


In [ ]:
# reshapeは、Tensorの形(数字の列や行)を変える
b = a.reshape(2,3)

print(b)
print(b.shape)

tensor([[0, 1, 2],
        [3, 4, 5]])
torch.Size([2, 3])


In [ ]:
import torch

x=torch.tensor([1,2,3])

print(x +1) # メモ: [1+1, 2+1, 3+1] -> 全部のに+1される
print(x * 2) # メモ: [1*2, 2*2, 3*2] -> 全部のが2倍される
print(x - 1) # メモ: [1-1, 2-1, 3-1] -> 全部から-1される
print(x / 2) # メモ: [1/2, 2/2, 3/2] -> 割り算すると自動で小数(float)になる！

tensor([2, 3, 4])
tensor([2, 4, 6])
tensor([0, 1, 2])
tensor([0.5000, 1.0000, 1.5000])


In [ ]:
y = torch.tensor([10,20,30])

print(x + y) # メモ: 同じ位置同士を足す [1+10, 2+20, 3+30] -> [11, 22, 33]
print(x * y)  # メモ: 同じ位置同士を掛ける [1*10, 2*20, 3*30] -> [10, 40, 90]

tensor([11, 22, 33])
tensor([10, 40, 90])


In [3]:
import torch

x = torch.arange(12)

print(x)
print(x.shape)


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])


In [4]:
x = torch.arange(12)

y = x.reshape(3,4) # 3行4列の2次元tensorに変形

print(y)
print(y.shape)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])


In [5]:
x = torch.arange(12)

y = x.view(4,3)

print(y)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])


In [ ]:
x = torch.tensor([[1,2,3],
                  [4,5,6]])
print(x[0]) #1行目を取り出す
print(x[1]) #2行目を取り出す
print(x[0,1]) #1行目の2列目を取り出す
print(x[1,2]) #2行目の3列目を取り出す

tensor([1, 2, 3])
tensor([4, 5, 6])
tensor(2)
tensor(6)


In [7]:
print(x[:,0]) #全ての行の1列目を取り出す

print(x[:,1]) #全ての行の2列目を取り出す

print(x[0,:]) #1行目の全ての列を取り出す

print(x[:,2]) #全ての行の3列目を取り出す

tensor([1, 4])
tensor([2, 5])
tensor([1, 2, 3])
tensor([3, 6])


In [8]:
x = torch.randn(2,3,4) # 2行3列4次元のランダムな値を持つtensorを作る

print(x.shape)

print(x.ndim) # tensorの次元数を出力する

torch.Size([2, 3, 4])
3


# 今日のまとめ

## 理解できたこと

- reshapeとは？
Tensorの形状（行と列の数や次元）を変更するメソッド。

メモリの連続性を気にせず安全に形状を変えることができる（必要な場合は自動でコピーを作成してくれる）。
- viewとは？
reshape と同様にTensorの形状を変更するメソッド。

元のTensorとメモリを共有するため処理が高速。ただし、メモリ上で要素が連続して並んでいない（contiguousでない）場合はエラーになることがある。
- indexingとは？
指定した位置の特定の要素（1つの値や1つの行など）をピンポイントで取り出す操作。

例: x[0, 1]（1行目の2列目を取り出す）
- slicingとは？
:（コロン）を使って、指定した範囲の要素を一括で切り出す操作。

例: x[:, 0]（すべての行の1列目だけをまとめて取り出す）
- shapeとndimの違い
shape: 各次元の要素数（サイズ）の並びを表す（例: torch.Size([2, 3, 4])）。

ndim: Tensor全体の次元の数（階数）を表す整数値（例: 3）。

## 分からなかったこと